# This workflow builds a multi-architecture docker image and pushes it to the github container registry
name: Docker build and push

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up maven token
      uses: s4u/maven-settings-action@v3.0.0
      with:
        servers: |
          [{
            "id": "gitlab-maven",
            "configuration": {
              "httpHeaders": {
                "property": {
                  "name": "Deploy-Token",
                  "value": "${{ secrets.MAVEN_TOKEN }}"
                }
              }
            }          
          }]

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: "linux/amd64,linux/arm64"
        tags: ghcr.io/ebi-gdp/globus-file-handler-cli:${{ github.event.release.tag_name }}
        secret-files: |
          "MAVEN_SETTINGS=/home/runner/.m2/settings.xml"
        file: "docker/crypt4gh/Dockerfile"
        build-args: |
            VERSION=${{ github.event.release.tag_name }}

    
    

    
