# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    branches: [actions]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set up maven token
      uses: s4u/maven-settings-action@v3.0.0
      with:
        servers: |
          [{
            "id": "serverId",
            "configuration": {
              "item1": "value1",
              "httpHeaders": {
                "property": {
                  "name": "Deploy-Token",
                  "value": "${{ secrets.MAVEN_TOKEN }}"
                }
              }
            }
          }]

    - name: Build with Maven
      run: mvn clean package

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
